### ISSUE TITLE
Anyone still working on this?

### ISSUE THREAD

**Issue by Vila333** [SpiderNight/TEvE-2#28]
Would be a shame if this game never sees the light. One of the best WC3 maps and one of my favourites, I can playtest for forever if you want me to.

**Comment by SpiderNight** [comment]
The project is not dead but has definantly slowed in development. We intend on finishing the project however (or atleast have it playable) in the next couple months.

**Comment by Vila333** [comment]
How's the progress? Need any playtesters?

**Comment by SpiderNight** [comment]
Unfortunately, I have lost motivation for this project, as it is a more than a little overwhelming for me to manage and keep a project like this under development while under the constant pressure of school (final year). I would of course like to finish this project as it was my favorite wc3 custom map, but the requirements to do so are, I'm afraid to say, are too much for me to handle.

For the time being and probably until the end of my school year, the project will be **on hold**.
